### PR TITLE
Fixed bug where you could create infinite shirts with only 5 wool

### PR DESCRIPTION
**Pull request by Thijsterhaar**
Will have to be tested before being merged.

### CODE REVIEW

**Comment by Thijsterhaar** [comment]
The bug is caused because the amount of wool is only checked before giving the user a popup. If the user opens the popup 100 times (which is possible because opening the popup does not reduce the amount of wool), then he can craft 100 shirts with only 5 wool.
In this PR the amount of wool in the inventory is checked again after selecting an option in the popup.

**Comment by CowedRevival** [comment]
Looks good to me

**Review by sethmlarson — APPROVED** [review]
LGTM

**Comment by Thijsterhaar** [comment]
Someone else has to merge the PR (I do not have that permission)

**Pull request merged**
